Repository oceanbase/oceanbase, pull requests merged in 2021-12, with the labels that each got.

#669 transfomer -> transformer
  docs/docs/docs-cn/5.overview/7.sql-engine-1/1.sql-request-execution-process-1.md
Labels: documentation, typos

#635 Fix [WhiteScan] [FLOATING_POINT_EQUALITY]
  src/sql/engine/expr/ob_expr_sqrt.cpp
Labels: sql

#673 Fix typo error: rountine_name -> routine_name
  docs/docs/docs-cn/10.sql-reference/5.sql-statement/40.GRANT.md
Labels: documentation, typos

#672 Update ob_log_plan.cpp
  src/sql/optimizer/ob_log_plan.cpp
Labels: typos, sql

#675 Fix typo error: OcenaBase -> OceanBase
  docs/docs/docs-cn/5.overview/7.sql-engine-1/3.query-optimization/2.join-algorithm-1/2.join-algorithm-4.md
Labels: documentation, typos

#538 Add chapter03 tutorial, about 'how to use oceanbase'.
  docs/docs/junior-training/ob-quick-start/chapter03/3.0.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.1.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.10.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.2.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.3.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.4.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.5.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.6.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.7.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.8.md
  docs/docs/junior-training/ob-quick-start/chapter03/3.9.md
Labels: documentation

#671 Fix typo error: transfomer -> transformer
  docs/docs/docs-cn/5.overview/7.sql-engine-1/6.sql-optimization-guide/1.sql-request-execution-process-2.md
Labels: documentation, typos

#609 fixed bug of issue #606
  src/sql/code_generator/ob_column_index_provider.cpp
Labels: white scan

#697 fixed #637, 'concurrentcy' typo error
  docs/docs/docs-cn/13.reference-guide/1.system-view/3.performance-view/62.v-sql.md
Labels: typos

#703 fixed #698, Use bash instead of dash in gen_type_name.sh on Ubuntu
  src/sql/parser/gen_type_name.sh
Labels: system compatibility, compilation

#696 fix misspelled word according to issue#277.
  src/election/ob_election_rpc.cpp
Labels: typos

#710 update 4.11.md v1
  docs/docs/junior-training/ob-quick-start/chapter04/4.11.md
Labels: documentation

#693 resolve issue#618
  src/sql/engine/expr/ob_expr_remainder.cpp
Labels: root, white scan
