Repository oceanbase/oceanbase, pull requests merged in 2021-08, with the labels that each got.

#278 modify mkdocs
  .github/workflows/publish-docs.yaml
  .gitignore
  docs/README.md
  mkdocs.md
  mkdocs.yml
Labels: documentation

#317 Fixed a wrong word in the comment
  src/sql/ob_sql.h
Labels: typos

#320 Fix typos in ob_macro_block.h
  src/storage/blocksstable/ob_macro_block.h
Labels: typos

#326 fix(ob_error): extended OB admin of ob_error
  tools/ob_error/README.md
  tools/ob_error/src/ob_error.cpp
  tools/ob_error/test/expect_result.result
Labels: enhancement
