Repository oceanbase/oceanbase, pull requests merged in 2021-09, with the labels that each got.

#333 Added some documents synchronized from ICMS, deleted some documents t…
  docs/docs/junior-training/index.md
  docs/mkdocs.yml
  docs/requirements.txt
Labels: documentation

#342 fix a core dump bug
  src/sql/resolver/dml/ob_select_resolver.cpp
Labels: bug

#344 去除alter外键约束时ob_ddl_timeout的约束，修改当前代码中遗失返回码和dead code的问题
  src/sql/code_generator/ob_expr_generator_impl.cpp
  src/sql/engine/cmd/ob_table_executor.cpp
  src/sql/resolver/ddl/ob_create_func_resolver.cpp
Labels: new feature

#350 add env checker script to check basic system info before install ocea…
  tools/scripts/env_checker.py
  tools/scripts/requirements.txt
  tools/scripts/requirements3.txt
Labels: new feature

#349 Remove oracle-related documents
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/1.table-operations-1.md
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/2.index-operations-1.md
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/3.insert-data-1.md
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/4.delete-data-1.md
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/5.update-data-1.md
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/6.query-data-1.md
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/7.submit-transaction-1.md
  docs/docs/docs-cn/2.quickstart/7.basic-operation-oracle-mode-1/8.roll-back-transactions-1.md
  docs/mkdocs.yml
Labels: documentation

#356 Fix invalid link in document
  docs/docs/docs-cn/2.quickstart/3.use-obd-to-obtain-the-oceanbase-database.md
  docs/docs/docs-cn/4.installation-and-deployment/1.deploy-the-distributed-oceanbase-cluster.md
  docs/docs/docs-cn/4.installation-and-deployment/12.install-the-oceanbase-database-by-using-the-rpm-package.md
  docs/docs/docs-cn/4.installation-and-deployment/13.get-the-oceanbase-database-by-using-source-code.md
  docs/docs/docs-cn/4.installation-and-deployment/4.optional-check-the-operating-system.md
Labels: bug

#360 Update index.md
  docs/docs/lectures/index.md
Labels: documentation

#319 call the destructor while memcpy is not safe in the pop_back() functi…
  deps/oblib/src/lib/container/ob_se_array.h
Labels: bug

#340 add recmd-config-pro doc
  docs/docs/docs-cn/4.installation-and-deployment/recommend-config-for-production.md
  docs/mkdocs.yml
Labels: documentation

#341 install-dir info
  docs/docs/docs-cn/15.community-contribution/1.how-to-contribute.md
  docs/docs/docs-cn/4.installation-and-deployment/installation-directory.md
  docs/mkdocs.yml
Labels: documentation
