Repository oceanbase/oceanbase, pull requests merged in 2021-11, with the labels that each got.

#418 refactor: remove unused code
  deps/oblib/src/common/CMakeLists.txt
  deps/oblib/src/common/lease/ob_lease_common.cpp
  deps/oblib/src/common/lease/ob_lease_common.h
  deps/oblib/src/lib/cbtree/btree_varchar_key.h
  src/storage/flashback/ob_flashback_engine.cpp
Labels: bug

#336 [doc]deploy ob manually
  docs/docs/docs-cn/4.installation-and-deployment/deploy-oceanbase-manually.md
  docs/mkdocs.yml
Labels: documentation

#490 error tool doc
  tools/ob_error/README.md
Labels: documentation

#495 fixed 494, Add <<Developer Manual>> to README
  CONTRIBUTING.md
  README-CN.md
  README.md
  docs/README.md
Labels: documentation

#487 fix license url in readme file
  README-CN.md
  README.md
Labels: documentation

#328 [doc]add clog faq
  docs/docs/docs-cn/ob-admin/about-ob-admin.md
  docs/docs/docs-cn/ob-admin/faq.md
Labels: documentation

#441 add MySQLClient to supported clients
  README.md
Labels: documentation

#499 Ob quick start
  docs/docs/junior-training/ob-quick-start/chapter01/1.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.0.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.1.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.10.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.11.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.12.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.13.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.2.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.3.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.4.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.5.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.6.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.7.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.8.md
  docs/docs/junior-training/ob-quick-start/chapter02/2.9.md
  docs/docs/junior-training/ob-quick-start/readme.md
Labels: documentation

#497 fixed 493, MkDocs encountered as error
  docs/README.md
  docs/requirements.txt
Labels: documentation

#560 fixed 502, ob_clog_mgr.h with misspelled word
  src/clog/ob_clog_mgr.h
Labels: typos

#556 Update 18.create-table.md
  docs/docs/docs-cn/10.sql-reference/5.sql-statement/18.create-table.md
Labels: bug, documentation

#563 fix mispelled timestamp
  src/clog/ob_log_type.cpp
Labels: typos

#559 fixed 525, ob_partition_log_service.cpp with misspelled word
  src/clog/ob_partition_log_service.cpp
Labels: typos

#558 Update ob_th_worker.cpp
  src/observer/omt/ob_th_worker.cpp
Labels: typos

#564 fixed ob_info_block_handler.h with misspelled word #511
  src/clog/ob_info_block_handler.h
Labels: typos

#567 fix issue 505, ob_partition_log_packet_handler.cpp with misspelled word
  src/clog/ob_partition_log_packet_handler.cpp
Labels: typos

#566 fix mispelled executor
  src/clog/ob_clog_mgr.cpp
Labels: typos

#578 Fix the problem of some links.
  docs/docs/junior-training/ob-quick-start/chapter01/1.md
Labels: documentation

#579 Update ob_partition_group.cpp
  src/storage/ob_partition_group.cpp
Labels: documentation

#583 Ob quick start chapter04
  docs/docs/junior-training/ob-quick-start/chapter04/4.0.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.1.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.10.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.11.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.12.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.2.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.3.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.4.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.5.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.6.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.7.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.8.md
  docs/docs/junior-training/ob-quick-start/chapter04/4.9.md
Labels: documentation

#577 fix mispelled cancel
  src/election/ob_election_timer.cpp
Labels: typos

#587 Fix typo #445
  src/clog/ob_log_archive_and_restore_driver.cpp
  src/clog/ob_log_archive_and_restore_driver.h
Labels: typos

#594 ob_ilog_storage.cpp with misspelled word
  src/clog/ob_ilog_storage.cpp
Labels: typos

#613 Remove redundant checks on ret
  src/sql/resolver/ddl/ob_ddl_resolver.cpp
Labels: bug

#589 fixed misspelled words #273
  src/election/ob_election_priority.cpp
Labels: typos

#588 fix typos
  src/clog/ob_log_block.h
Labels: typos

#607 fix misspelled word in #451
  src/clog/ob_log_cascading_mgr.cpp
Labels: typos
