Repository oceanbase/oceanbase, pull requests merged in 2022-04, with the labels that each got.

#784 oceanbase can run in low memory system now
  deps/oblib/src/lib/ob_running_mode.cpp
Labels: enhancement

#851 add support for loongarch64
  cmake/Env.cmake
  deps/easy/src/include/easy_atomic.h
  deps/easy/src/io/ev.c
  deps/easy/src/util/easy_time.c
  deps/oblib/src/lib/CMakeLists.txt
  deps/oblib/src/lib/async/ev.c
  deps/oblib/src/lib/atomic/atomic128.h
  deps/oblib/src/lib/atomic/ob_atomic.h
  deps/oblib/src/lib/checksum/ob_crc64.cpp
  deps/oblib/src/lib/coro/co_utils.h
  deps/oblib/src/lib/coro/context/asm/jump_loongarch64_sysv_elf_gas.S
  deps/oblib/src/lib/coro/context/asm/make_loongarch64_sysv_elf_gas.S
  deps/oblib/src/lib/coro/context/asm/ontop_loongarch64_sysv_elf_gas.S
  deps/oblib/src/lib/list/ob_atomic_list.h
  deps/oblib/src/lib/utility/utility.h
  src/election/ob_election.h
  src/election/ob_election_group.h
Labels: system compatibility, compilation

#861 fix standalone docker bugs
  tools/docker/standalone/Dockerfile
  tools/docker/standalone/boot/_boot
  tools/docker/standalone/boot/boot-tmp.yaml
Labels: docker
