Repository oceanbase/oceanbase, pull requests merged in 2022-03, with the labels that each got.

#787 support 2c8g docker
  tools/docker/mini/Dockerfile
  tools/docker/mini/README.md
  tools/docker/mini/boot/boot-tmp.yaml
  tools/docker/mini/boot/init_tenant-tmp.sql
Labels: docker

#788 fix typos “ocena->ocean” #646
  docs/docs-cn/12.sql-optimization-guide-1/4.sql-optimization-1/5.query-optimization-2/2.join-algorithm-5/2.join-algorithm-6.md
Labels: typos

#789 fix bug：连续多行的单行注释报错 bug #783
  src/sql/parser/ob_parser.cpp
Labels: bug-P2

#796 fixed 795, add community to README
  README-CN.md
  README.md
Labels: documentation

#799 add default engine for TABLES
  src/share/inner_table/ob_inner_table_schema.20001_20050.cpp
  src/share/inner_table/ob_inner_table_schema_def.py
Labels: enhancement

#853 standalone docker image
  tools/docker/mini/README-CN.md
  tools/docker/mini/README.md
  tools/docker/standalone/Dockerfile
  tools/docker/standalone/README-CN.md
  tools/docker/standalone/README.md
  tools/docker/standalone/boot/_boot
  tools/docker/standalone/boot/_env
  tools/docker/standalone/boot/boot-mini-tmp.yaml
  tools/docker/standalone/boot/boot-tmp.yaml
  tools/docker/standalone/boot/init_tenant_user.sql
  tools/docker/standalone/boot/ob-mysql
Labels: docker
