Repository oceanbase/oceanbase, pull requests merged in 2022-11, with the labels that each got.

#1136 fix obd.sh
  deps/init/oceanbase.el7.aarch64.deps
  deps/init/oceanbase.el7.x86_64.deps
  deps/init/oceanbase.el8.aarch64.deps
  deps/init/oceanbase.el8.x86_64.deps
  src/sql/engine/expr/ob_expr_to_outfile_row.cpp
  tools/deploy/init_create_tenant_routines.sql
  tools/deploy/obd.sh
Labels: OceanBase competition

#1142 fix make DESTDIR install problem
  CMakeLists.txt
  build.sh
  cmake/RPM.cmake
Labels: OceanBase competition

#1139 Declares TS3.1 and Centos 8 compatible
  deps/init/dep_create.sh
Labels: system compatibility, compilation

#1130 fix #1129: mispell, is_file_tpe() -> is_file_type()
  src/storage/blocksstable/ob_index_block_builder.h
Labels: bug

#1176 [Issue1159] fix typos: colume -> column
  src/pl/sys_package/ob_dbms_stats.cpp
  src/share/ob_tablet_replica_checksum_operator.cpp
  src/sql/ob_select_stmt_printer.cpp
  src/sql/parser/sql_parser_mysql_mode.y
Labels: bug
