Repository oceanbase/oceanbase, pull requests merged in 2022-08, with the labels that each got.

#1018 fix Rocky is not supported #1014
  deps/3rd/dep_create.sh
Labels: system compatibility, compilation

#1048 fixed 1047, Rewrite the readme.
  README-CN.md
  README.md
Labels: documentation

#1045 fix float value directly tested for equality
  src/sql/engine/expr/ob_expr_mod.cpp
Labels: bug
