Repository oceanbase/oceanbase, pull requests merged in 2023-05, with the labels that each got.

#1370 fix: easy alloc memory of incorrect size
  deps/easy/src/util/easy_pool.c
  deps/easy/test/util/easy_pool_test.c
Labels: type: bug, status: ci running

#1380 fix incorrect URL about release in README
  README.md
Labels: status: ci running

#1397 Fix issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: status: merging
